"""Weekly learning report model (D9 学习周报，产品设计规划-2026-08 §4).

One row per user per ISO week, generated by the Monday beat task from
LearningRecord / LearningEvent aggregates. Immutable once generated
(re-running the generator skips existing weeks).
"""

import uuid
from datetime import UTC, date, datetime

from sqlalchemy import JSON, Date, DateTime, Float, ForeignKey, Integer, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class WeeklyReport(Base):
    __tablename__ = "weekly_reports"
    __table_args__ = (UniqueConstraint("user_id", "week_start", name="uq_weekly_report_user_week"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )

    # Monday of the ISO week this report covers
    week_start: Mapped[date] = mapped_column(Date, nullable=False, index=True)

    # Aggregates for the week (Mon–Sun)
    study_days: Mapped[int] = mapped_column(Integer, default=0)
    total_minutes: Mapped[int] = mapped_column(Integer, default=0)
    new_words: Mapped[int] = mapped_column(Integer, default=0)
    reviewed_words: Mapped[int] = mapped_column(Integer, default=0)
    videos_completed: Mapped[int] = mapped_column(Integer, default=0)
    streak_at_week_end: Mapped[int] = mapped_column(Integer, default=0)

    # Week-over-week change in total_minutes (%); None for the first week
    delta_minutes_pct: Mapped[float | None] = mapped_column(Float, nullable=True)

    # 7 elements Mon→Sun: [{"date": "2026-08-24", "minutes": 35}, ...]
    daily_minutes: Mapped[list | None] = mapped_column(JSON, nullable=True)
    # 7 elements Mon→Sun: [{"date": "2026-08-24", "words": 5}, ...] — 新学词汇曲线数据源
    daily_new_words: Mapped[list | None] = mapped_column(JSON, nullable=True)

    # 本周亮点（单日最长学习时长文案；无数据为 "坚持就是胜利"）
    highlight: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(UTC))

    # relationships
    user = relationship("User")
