"""Get fresh YouTube cookies using Playwright CLI.

Usage:
    # Option 1: Use existing browser session (recommended)
    python get_youtube_cookies.py --from-session

    # Option 2: Open browser and wait for manual login
    python get_youtube_cookies.py --open-browser

    # Option 3: Convert existing Playwright state file
    python get_youtube_cookies.py --from-state ./state.json

    # Specify output path
    python get_youtube_cookies.py --output ./youtube_cookies.txt
"""

import argparse
import json
import logging
import shutil
import subprocess
import sys
import time
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

DEFAULT_OUTPUT = "./youtube_cookies.txt"
PLAYWRIGHT_STATE_FILE = ".playwright-cli/session-state.json"

# Find playwright-cli executable (handles .CMD on Windows)
PLAYWRIGHT_CLI = shutil.which("playwright-cli") or "playwright-cli"


def _run_cmd(args: list[str], check: bool = True) -> subprocess.CompletedProcess:
    """Run playwright-cli command with proper executable resolution."""
    cmd = [PLAYWRIGHT_CLI] + args
    return subprocess.run(cmd, capture_output=True, text=True, check=check)


def run_playwright_cmd(args: list[str], check: bool = True) -> str:
    """Run a playwright-cli command and return stdout."""
    result = _run_cmd(args, check=check)
    return result.stdout


def is_browser_open() -> bool:
    """Check if a playwright-cli browser session is active."""
    try:
        result = _run_cmd(["list"], check=False)
        output = result.stdout + result.stderr
        return "status: open" in output.lower()
    except FileNotFoundError:
        return False


def is_youtube_logged_in() -> bool:
    """Check if YouTube LOGIN_INFO cookie exists in current session."""
    try:
        stdout = run_playwright_cmd(["cookie-get", "LOGIN_INFO"], check=False)
        return "LOGIN_INFO" in stdout and len(stdout.strip()) > 20
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


def open_youtube_persistent() -> None:
    """Open YouTube in persistent browser via playwright-cli."""
    logger.info("Opening YouTube with persistent profile...")
    run_playwright_cmd(["open", "https://www.youtube.com", "--persistent"], check=False)
    logger.info("Browser opened. Please log in to YouTube if not already logged in.")


def save_session_state(output_path: str = PLAYWRIGHT_STATE_FILE) -> str:
    """Save current browser session state to JSON."""
    logger.info("Saving browser session state...")
    run_playwright_cmd(["state-save", output_path])
    return output_path


def convert_to_netscape(state_path: str, output_path: str) -> bool:
    """Convert Playwright JSON state to Netscape cookies format."""
    state_file = Path(state_path)
    if not state_file.exists():
        logger.error(f"State file not found: {state_path}")
        return False

    try:
        with open(state_file, "r", encoding="utf-8") as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        logger.error(f"Invalid JSON in state file: {e}")
        return False

    cookies = data.get("cookies", [])
    if not cookies:
        logger.error("No cookies found in state file")
        return False

    # Write in Netscape format
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by Playwright.\n\n")

        for cookie in cookies:
            domain = cookie.get("domain", "")
            # Netscape format: domain, flag, path, secure, expiry, name, value
            flag = "TRUE" if domain.startswith(".") else "FALSE"
            secure = "TRUE" if cookie.get("secure") else "FALSE"
            expiry = cookie.get("expires", 0)
            if expiry == 0 or expiry == -1:
                expiry_str = "0"
            else:
                expiry_str = str(int(expiry))
            name = cookie.get("name", "")
            value = cookie.get("value", "")
            path = cookie.get("path", "/")

            f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry_str}\t{name}\t{value}\n")

    # Show stats
    yt_cookies = [c for c in cookies if "youtube" in c.get("domain", "").lower()]
    google_cookies = [c for c in cookies if "google" in c.get("domain", "").lower()]

    logger.info(f"Cookies saved to: {output_path}")
    logger.info(f"  Total cookies: {len(cookies)}")
    logger.info(f"  YouTube cookies: {len(yt_cookies)}")
    logger.info(f"  Google cookies: {len(google_cookies)}")

    # Check for key login cookies
    key_cookies = ["LOGIN_INFO", "SID", "__Secure-1PSID", "HSID", "SSID"]
    found = {name: any(c.get("name") == name for c in cookies) for name in key_cookies}
    logger.info("  Key cookies:")
    for name, ok in found.items():
        status = "✓" if ok else "✗"
        logger.info(f"    {status} {name}")

    return True


def get_cookies_from_session(output_path: str) -> bool:
    """Extract cookies from an existing playwright-cli session."""
    if not is_browser_open():
        logger.error("No browser session found. Run with --open-browser first.")
        return False

    if not is_youtube_logged_in():
        logger.warning("LOGIN_INFO cookie not found. You may not be logged in to YouTube.")
        response = input("Continue anyway? [y/N]: ")
        if response.lower() != "y":
            return False

    # Save state and convert
    state_path = save_session_state()
    success = convert_to_netscape(state_path, output_path)

    # Clean up temp state file
    try:
        Path(state_path).unlink()
    except OSError:
        pass

    return success


def get_cookies_with_browser(output_path: str, wait_seconds: int = 60) -> bool:
    """Open browser, wait for login, then extract cookies."""
    open_youtube_persistent()
    logger.info(f"Waiting {wait_seconds} seconds for you to log in...")
    time.sleep(wait_seconds)
    return get_cookies_from_session(output_path)


def get_cookies_from_state_file(state_path: str, output_path: str) -> bool:
    """Convert an existing Playwright state file to Netscape format."""
    return convert_to_netscape(state_path, output_path)


def main():
    parser = argparse.ArgumentParser(
        description="Get YouTube cookies via Playwright CLI",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Use existing browser session (fastest)
  python get_youtube_cookies.py --from-session

  # Open browser and wait for manual login
  python get_youtube_cookies.py --open-browser --wait 120

  # Convert existing Playwright state file
  python get_youtube_cookies.py --from-state ./my-state.json
        """
    )
    parser.add_argument(
        "--output", "-o",
        default=DEFAULT_OUTPUT,
        help=f"Output cookies file path (default: {DEFAULT_OUTPUT})"
    )
    parser.add_argument(
        "--from-session", "-s",
        action="store_true",
        help="Extract cookies from an existing playwright-cli session"
    )
    parser.add_argument(
        "--open-browser", "-b",
        action="store_true",
        help="Open YouTube in browser and wait for manual login"
    )
    parser.add_argument(
        "--from-state",
        metavar="PATH",
        help="Convert an existing Playwright state JSON file"
    )
    parser.add_argument(
        "--wait", "-w",
        type=int, default=60,
        help="Seconds to wait for manual login (default: 60)"
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable verbose logging"
    )

    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    # Default to --from-session if no mode specified
    if not any([args.from_session, args.open_browser, args.from_state]):
        args.from_session = True

    success = False

    if args.from_state:
        success = get_cookies_from_state_file(args.from_state, args.output)
    elif args.open_browser:
        success = get_cookies_with_browser(args.output, args.wait)
    elif args.from_session:
        success = get_cookies_from_session(args.output)

    if success:
        logger.info("Done! Cookies saved successfully.")
        sys.exit(0)
    else:
        logger.error("Failed to save cookies.")
        sys.exit(1)


if __name__ == "__main__":
    main()
