"""Alibaba Cloud Dypnsapi 短信认证服务 — SMS verification-code service.

Uses the 号码认证 (Dypnsapi) 短信认证 APIs:
  * ``SendSmsVerifyCode`` — sends the code; the code is GENERATED BY ALIYUN
    (``TemplateParam`` carries the ``##code##`` placeholder) and verified
    server-side by Aliyun.
  * ``CheckSmsVerifyCode`` — verifies a submitted code against the one
    Aliyun sent for that phone number.

Templates per purpose (register / change_phone / reset_password) map to the
console 赠送模板 (100001/100002/100003) and must use the 系统赠送签名
(``ALIYUN_SMS_SIGN_NAME``); custom signatures are not supported by this
product line.

Redis keys
----------
- ``sms:code:{phone}:{purpose}`` — dev-fake only: the fixed code (TTL from
  ``settings.sms_code_expire_seconds``). Production does not store codes
  locally — Aliyun manages generation and verification.
- ``sms:cooldown:{phone}:{purpose}`` — per-phone-per-purpose send cooldown
  (set by the route layer, 60 s).

Dev fallback: when NOT in production and ``sms_login_enabled`` is False
(or AK/SK are unset), ``send_verify_code`` logs a fixed code and stores it
in Redis; ``verify_code`` accepts ``"1234"``.  This lets phone login work
locally with no Aliyun credentials or spend.

Security: the dev-fake code path is **never** active in production — a
production deployment missing SMS credentials fails closed (send returns
502, verify always False) instead of silently accepting the fixed code.
"""

import threading

import structlog

from app.core.config import get_settings
from app.core.logging import mask_phone
from app.core.redis import get_redis

logger = structlog.get_logger(__name__)

# Lazy imports for Alibaba Cloud SDK — may not be installed in dev/test.
_dypnsapi_models = None
_DypnsapiClient = None
_open_api_models = None
_tea_util_models = None


def _ensure_sdk():
    """Import Alibaba Cloud SDK on first real use (avoids ImportError in dev/test)."""
    global _dypnsapi_models, _DypnsapiClient, _open_api_models, _tea_util_models
    if _dypnsapi_models is None:
        from alibabacloud_dypnsapi20170525 import models as dypnsapi_models
        from alibabacloud_dypnsapi20170525.client import Client as DypnsapiClient
        from alibabacloud_tea_openapi import models as open_api_models
        from alibabacloud_tea_util import models as util_models

        _dypnsapi_models = dypnsapi_models
        _DypnsapiClient = DypnsapiClient
        _open_api_models = open_api_models
        _tea_util_models = util_models


# Fixed code accepted in dev-fake mode (no Aliyun credentials configured).
_DEV_FAKE_CODE = "1234"

# Template-code mapping by purpose (console 赠送模板 IDs).
_PURPOSE_TEMPLATES = {
    "register": "aliyun_sms_template_register",
    "change_phone": "aliyun_sms_template_change_phone",
    "reset_password": "aliyun_sms_template_reset_password",
}

# SendSmsVerifyCode.CodeType: 1 = 纯数字（默认）。
_CODE_TYPE_DIGITS = 1

_client = None
_singleton_lock = threading.Lock()


def get_sms_client():
    """Lazy thread-safe singleton for the Dypnsapi client."""
    global _client
    if _client is None:
        with _singleton_lock:
            if _client is None:
                _ensure_sdk()
                settings = get_settings()
                config = _open_api_models.Config(
                    access_key_id=settings.aliyun_sms_access_key,
                    access_key_secret=settings.aliyun_sms_secret_key,
                    endpoint=settings.aliyun_sms_endpoint,
                )
                _client = _DypnsapiClient(config)
    return _client


def _real_send_enabled() -> bool:
    """True only when SMS login is enabled AND AK/SK are configured."""
    settings = get_settings()
    return bool(settings.sms_login_enabled and settings.aliyun_sms_access_key and settings.aliyun_sms_secret_key)


def _dev_fake_enabled() -> bool:
    """True only when the fixed-code dev-fake is allowed.

    Dev-fake (accept ``"1234"``) exists so local development / CI can run
    phone flows without Aliyun credentials. It must NEVER be active in
    production — a production box missing SMS credentials should fail
    closed (send-code 502 / verify False), not accept a publicly-known
    fixed code that would let anyone log into any phone account.
    """
    settings = get_settings()
    if settings.env == "production":
        return False
    return not _real_send_enabled()


async def send_verify_code(phone: str, purpose: str = "register") -> None:
    """Send an SMS verification code to ``phone`` for the given ``purpose``.

    Production: Aliyun Dypnsapi ``SendSmsVerifyCode`` generates and delivers
    the code (``##code##`` placeholder); nothing is stored locally.  Dev-fake
    mode stores the fixed code ``"1234"`` in Redis and makes no Aliyun call.
    Raises RuntimeError on Aliyun API failure so the route can surface a 502.
    """
    settings = get_settings()
    redis = get_redis()
    ttl = settings.sms_code_expire_seconds

    if _dev_fake_enabled():
        # Store code in Redis (overwrite any previous code for this phone+purpose).
        try:
            await redis.set(f"sms:code:{phone}:{purpose}", _DEV_FAKE_CODE, ex=ttl)
        except Exception:
            # Fail-open: Redis outage must not block SMS sending.
            logger.warning("sms_code_store_failed", phone=mask_phone(phone), purpose=purpose)
        logger.info("[sms-fake] code=%s for %s (purpose=%s)", _DEV_FAKE_CODE, mask_phone(phone), purpose)
        return

    # Resolve template code from settings based on purpose.
    template_attr = _PURPOSE_TEMPLATES.get(purpose)
    if not template_attr:
        raise ValueError(f"Unknown SMS purpose: {purpose}")
    template_code = getattr(settings, template_attr)

    # Template param: {"code":"##code##","min":"5"} — ##code## is the
    # placeholder Aliyun replaces with the code IT generates (required for
    # CheckSmsVerifyCode to work; a concrete value would NOT be verifiable).
    minutes = str(max(1, ttl // 60))
    template_param = f'{{"code":"##code##","min":"{minutes}"}}'

    client = get_sms_client()
    _ensure_sdk()
    request = _dypnsapi_models.SendSmsVerifyCodeRequest(
        phone_number=phone,
        sign_name=settings.aliyun_sms_sign_name,
        template_code=template_code,
        template_param=template_param,
        code_type=_CODE_TYPE_DIGITS,
        valid_time=ttl,
    )
    try:
        # RuntimeOptions is REQUIRED here: alibabacloud_tea_openapi 0.4.x
        # crashes with ``'NoneType' object has no attribute 'key'`` when the
        # runtime arg is None (runtime.key is dereferenced unconditionally).
        runtime = _tea_util_models.RuntimeOptions()
        resp = await client.send_sms_verify_code_with_options_async(request, runtime)
    except Exception as exc:
        msg = getattr(exc, "message", str(exc))
        logger.error("sms_send_failed", phone=mask_phone(phone), purpose=purpose, error=msg)
        raise RuntimeError(f"SMS send failed: {msg}") from exc

    body = getattr(resp, "body", None)
    resp_code = getattr(body, "code", None) if body else None
    if resp_code != "OK":
        message = getattr(body, "message", "") if body else ""
        logger.error("sms_send_non_ok", phone=mask_phone(phone), purpose=purpose, code=resp_code, message=message)
        raise RuntimeError(f"SMS send failed: {resp_code} {message}")


async def verify_code(phone: str, code: str, purpose: str = "register") -> bool:
    """Verify an SMS code against Aliyun (or accept the dev-fake code).

    Production: Dypnsapi ``CheckSmsVerifyCode`` verifies server-side; the
    code Aliyun sent for ``phone`` is consumed on success (DuplicatePolicy
    default: a newer send invalidates the older code).
    """
    redis = get_redis()
    key = f"sms:code:{phone}:{purpose}"

    # Dev-fake mode: accept the fixed code without checking Redis. Never
    # active in production (see _dev_fake_enabled) — a production box
    # missing SMS credentials fails closed (no code was ever sent).
    if _dev_fake_enabled():
        if code != _DEV_FAKE_CODE:
            return False
        # Also try to delete from Redis (best-effort) to prevent reuse.
        try:
            await redis.delete(key)
        except Exception:
            pass
        return True

    # Production: ask Aliyun to verify the code it generated.
    client = get_sms_client()
    _ensure_sdk()
    request = _dypnsapi_models.CheckSmsVerifyCodeRequest(
        phone_number=phone,
        verify_code=code,
    )
    try:
        runtime = _tea_util_models.RuntimeOptions()
        resp = await client.check_sms_verify_code_with_options_async(request, runtime)
    except Exception as exc:
        msg = getattr(exc, "message", str(exc))
        # Verification failure must fail closed — never accept on transport error.
        logger.warning("sms_verify_failed", phone=mask_phone(phone), purpose=purpose, error=msg)
        return False

    body = getattr(resp, "body", None)
    if getattr(body, "code", None) != "OK":
        logger.warning("sms_verify_non_ok", phone=mask_phone(phone), purpose=purpose, code=getattr(body, "code", None))
        return False
    model = getattr(body, "model", None)
    return bool(model is not None and getattr(model, "verify_result", None) == "PASS")
