"""Advanced Douyin video/audio extraction using Playwright.

Ported from translate-tool's app/downloader/cookies.py and app/converter/video.py.
Uses Playwright stealth mode, API interception, and embedded JSON parsing
to reliably extract video metadata and audio from Douyin pages.

All async code from translate-tool is wrapped into sync interfaces to match
Speaking's Celery-based architecture.
"""

import asyncio
import json
import structlog
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Optional
from urllib.parse import urlparse

from app.core.config import get_settings
from .exceptions import AudioExtractionError

logger = structlog.get_logger()

# ── Shared ffmpeg audio encoding flags for PCM 16kHz mono WAV ──
_FFMPEG_WAV_ARGS = ["-vn", "-acodec", "pcm_s16le", "-ar", "16000", "-ac", "1"]

# Windows no-window flag
_NO_WINDOW = 0
if hasattr(subprocess, "CREATE_NO_WINDOW"):
    _NO_WINDOW = subprocess.CREATE_NO_WINDOW

# ── Browser singletons (process-wide cache) ──
_BROWSER = None
_CONTEXT = None
_BROWSER_INIT_LOCK = asyncio.Lock()

_COOKIE_WAIT_SECONDS = 3

_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/131.0.0.0 Safari/537.36"
)

# ── Cookie / Header utilities ──


def _cookies_to_netscape(cookies: list[dict]) -> str:
    """Convert Playwright cookies to Netscape-format text."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Auto-generated by Speaking Douyin extractor",
        "",
    ]
    for c in cookies:
        domain = c.get("domain", "")
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = str(int(c.get("expires", 0))) if c.get("expires", 0) != -1 else "0"
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


def _netscape_to_cookie_header(netscape_text: str) -> str:
    """Convert Netscape-format cookies to a single Cookie: header value for ffmpeg."""
    if not netscape_text:
        return ""
    pairs = []
    for line in netscape_text.strip().split("\n"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) >= 7:
            name, value = parts[5], parts[6]
            pairs.append(f"{name}={value}")
    return "; ".join(pairs)


# ── Browser lifecycle (async internals, exposed via sync wrappers) ──


async def _ensure_browser_async():
    """Lazy-init the Playwright browser (shared process-wide)."""
    global _BROWSER, _CONTEXT

    if _BROWSER is not None:
        return _BROWSER, _CONTEXT

    async with _BROWSER_INIT_LOCK:
        if _BROWSER is not None:
            return _BROWSER, _CONTEXT

        try:
            from playwright.async_api import async_playwright
        except ImportError:
            raise RuntimeError(
                "playwright is not installed. Install: pip install playwright && playwright install chromium"
            )

        p = await async_playwright().start()
        _BROWSER = await p.chromium.launch(
            headless=True,
            args=[
                "--disable-blink-features=AutomationControlled",
                "--no-sandbox",
                "--disable-dev-shm-usage",
            ],
        )
        _CONTEXT = await _BROWSER.new_context(
            user_agent=_USER_AGENT,
            viewport={"width": 1920, "height": 1080},
            locale="zh-CN",
        )
        try:
            from playwright_stealth import StealthConfig, stealth_async
            await stealth_async(_CONTEXT, StealthConfig())
            logger.info("Playwright stealth mode enabled")
        except ImportError:
            logger.warning("playwright_stealth not installed, continuing without stealth")

        logger.info("Playwright browser initialized")
        return _BROWSER, _CONTEXT


def _ensure_browser():
    """Sync wrapper for lazy-init browser."""
    if _BROWSER is not None:
        return _BROWSER, _CONTEXT

    async def _init():
        return await _ensure_browser_async()

    try:
        browser, context = asyncio.run(_init())
    except RuntimeError:
        # Fallback if there's already a running event loop
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            browser, context = loop.run_until_complete(_init())
        finally:
            loop.close()

    return browser, context


def close_browser():
    """Cleanup on shutdown."""
    global _BROWSER, _CONTEXT
    if _BROWSER:
        try:
            asyncio.run(_BROWSER.close())
        except Exception:
            pass
        _BROWSER = None
        _CONTEXT = None
        logger.info("Playwright browser closed")


# ── Douyin metadata extraction ──


def _extract_douyin_from_html(html: str) -> Optional[dict]:
    """Extract Douyin video metadata from embedded page JSON.

    Douyin embeds data in <script id="RENDER_DATA"> as URL-encoded JSON.
    """
    import urllib.parse

    # Method 1: RENDER_DATA
    m = re.search(r'<script\s+id="RENDER_DATA"[^>]*>(.*?)</script>', html, re.DOTALL)
    if m:
        try:
            raw = urllib.parse.unquote(m.group(1))
            data = json.loads(raw)
        except Exception:
            return None

        # Navigate the nested structure to video data
        # Typical path: app > videoInfoRes > item_list[0]
        app = data.get("app", {})
        video_info = app.get("videoInfoRes", {}) or app.get("aweme", {}).get("detail", {})
        item_list = video_info.get("item_list", [])
        if item_list:
            return _parse_douyin_item(item_list[0])
        # Sometimes in aweme_detail directly
        aweme = video_info.get("aweme_detail", {})
        if aweme:
            return _parse_douyin_item(aweme)

    # Method 2: _ROUTER_DATA
    m = re.search(r'window\._ROUTER_DATA\s*=\s*({.*?});', html, re.DOTALL)
    if m:
        try:
            data = json.loads(m.group(1))
        except Exception:
            return None
        # Navigate loaderData
        loader = data.get("loaderData", {})
        for key in loader:
            if "video" in key.lower():
                item = loader[key].get("videoInfoRes", {}).get("item_list", [])
                if item:
                    return _parse_douyin_item(item[0])

    return None


def _parse_douyin_item(item: dict) -> Optional[dict]:
    """Parse a single Douyin video item into a common format."""
    video = item.get("video", {})
    if not video:
        return None

    # Find best video URL
    play_addr = video.get("play_addr", {}) or video.get("play_api", {})
    url_list = play_addr.get("url_list", []) or play_addr.get("url", [])
    # Prefer highest quality (last in list, or take first)
    video_url = None
    if isinstance(url_list, list) and url_list:
        video_url = url_list[-1]  # Often last is highest quality
    elif isinstance(url_list, str):
        video_url = url_list

    # Also check download_addr for no-watermark version
    download_addr = video.get("download_addr", {})
    dl_url_list = download_addr.get("url_list", [])
    if dl_url_list:
        video_url = dl_url_list[-1]

    if not video_url:
        return None

    author = item.get("author", {})
    music = item.get("music", {})

    # Duration is in milliseconds in Douyin API
    duration_raw = video.get("duration", 0)
    duration = duration_raw / 1000 if duration_raw else 0

    return {
        "id": str(item.get("aweme_id", "")),
        "title": item.get("desc", "") or item.get("preview_title", ""),
        "duration": duration,
        "video_url": video_url,
        "thumbnail": video.get("cover", {}).get("url_list", [""])[0] if video.get("cover") else "",
        "uploader": author.get("nickname", ""),
        "uploader_id": author.get("uid", ""),
        "width": video.get("width", 0),
        "height": video.get("height", 0),
        "like_count": item.get("statistics", {}).get("digg_count", 0),
        "comment_count": item.get("statistics", {}).get("comment_count", 0),
        "share_count": item.get("statistics", {}).get("share_count", 0),
    }


def _extract_douyin_from_api(response_body: str) -> Optional[dict]:
    """Extract Douyin video metadata from intercepted API response."""
    try:
        data = json.loads(response_body)
    except json.JSONDecodeError:
        return None

    aweme = data.get("aweme_detail", {})
    if aweme:
        return _parse_douyin_item(aweme)
    return None


# ── Async core (internal) ──


async def _fetch_douyin_video_data_async(url: str) -> dict:
    """Fetch Douyin video metadata via Playwright (async core).

    1. Opens the video page in a real browser
    2. Intercepts the /aweme/v1/web/aweme/detail/ API response for video data
    3. Falls back to extracting from embedded page JSON
    4. Also collects all cookies for yt-dlp fallback

    Returns a dict with video metadata (id, title, duration, video_url, etc.)
    """
    _, context = await _ensure_browser_async()
    page = await context.new_page()

    api_data = None
    api_error = None

    async def handle_response(response):
        nonlocal api_data, api_error
        if "/aweme/v1/web/aweme/detail/" in response.url:
            try:
                body = await response.text()
                data = _extract_douyin_from_api(body)
                if data:
                    api_data = data
                    logger.info("Intercepted Douyin API response successfully")
                else:
                    api_error = f"API returned data without aweme_detail: {body[:200]}"
            except Exception as e:
                api_error = str(e)

    page.on("response", handle_response)

    html = ""
    try:
        logger.info("Navigating to Douyin video", url=url)
        await page.goto(url, wait_until="domcontentloaded", timeout=30000)

        # Wait for the video player or RENDER_DATA to appear
        try:
            await page.wait_for_selector(
                'script[id="RENDER_DATA"], video, .video-player',
                timeout=15000,
            )
            logger.debug("Page content loaded")
        except Exception:
            logger.debug("No video selector found, proceeding anyway")

        # Extra wait for API calls to complete
        await asyncio.sleep(_COOKIE_WAIT_SECONDS)

        # Get cookies regardless (for yt-dlp fallback)
        cookies = await context.cookies()
        cookie_names = {c["name"] for c in cookies}
        logger.info("Page cookies collected", cookie_names=cookie_names)

        # Get page HTML for embedded data fallback
        html = await page.content()

        # Extract localStorage tokens
        host = urlparse(url).netloc.lower().replace("www.", "")
        if "douyin.com" in host:
            try:
                ms_token = await page.evaluate("() => localStorage.getItem('msToken') || ''")
                if ms_token:
                    cookies.append({
                        "name": "msToken",
                        "value": ms_token,
                        "domain": ".douyin.com",
                        "path": "/",
                        "expires": -1,
                        "httpOnly": False,
                        "secure": True,
                        "sameSite": "None",
                    })
                    logger.debug("Extracted localStorage token: msToken")
            except Exception:
                pass

    finally:
        await page.close()

    # Build result
    result = api_data or _extract_douyin_from_html(html)

    if not result:
        # Check what went wrong
        error_detail = api_error or "No data found in API or page"
        logger.error("Failed to extract Douyin video data", detail=error_detail)
        raise AudioExtractionError(
            f"Could not extract video data from Douyin page. "
            f"The video may be private, deleted, or geo-restricted.\n"
            f"Details: {error_detail}"
        )

    # Attach cookies for any follow-up downloads
    result["cookies"] = _cookies_to_netscape(cookies)

    logger.info(
        "Douyin video extracted",
        video_id=result['id'],
        title=result['title'][:50],
        duration=result['duration'],
    )
    return result


# ── Sync public interface ──


def fetch_douyin_video_data(url: str) -> dict:
    """Fetch Douyin video metadata via Playwright (sync wrapper).

    Returns a dict with video metadata:
    {
        "id": str,
        "title": str,
        "duration": float,  # seconds
        "video_url": str,
        "thumbnail": str,
        "uploader": str,
        "uploader_id": str,
        "width": int,
        "height": int,
        "like_count": int,
        "comment_count": int,
        "share_count": int,
        "cookies": str,  # Netscape format
    }
    """
    async def _run():
        return await _fetch_douyin_video_data_async(url)

    try:
        return asyncio.run(_run())
    except RuntimeError:
        # Fallback if there's already a running event loop
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            return loop.run_until_complete(_run())
        finally:
            loop.close()


def get_ytdlp_cookie_file(url: str) -> str:
    """Fetch fresh cookies via Playwright and save as Netscape format for yt-dlp.

    Returns the path to the temporary cookie file.
    """
    settings = get_settings()

    async def _run():
        _, context = await _ensure_browser_async()
        page = await context.new_page()

        try:
            logger.info("Fetching cookies from", url=url)
            await page.goto(url, wait_until="domcontentloaded", timeout=30000)
            await asyncio.sleep(_COOKIE_WAIT_SECONDS)

            cookies = await context.cookies()

            # Extract site-specific localStorage tokens as cookies
            host = urlparse(url).netloc.lower().replace("www.", "")
            if "douyin.com" in host:
                try:
                    ms_token = await page.evaluate("() => localStorage.getItem('msToken') || ''")
                    if ms_token:
                        cookies.append({
                            "name": "msToken",
                            "value": ms_token,
                            "domain": ".douyin.com",
                            "path": "/",
                            "expires": -1,
                            "httpOnly": False,
                            "secure": True,
                            "sameSite": "None",
                        })
                        logger.debug("Extracted localStorage token: msToken")
                except Exception:
                    pass

            cookie_text = _cookies_to_netscape(cookies)

            domain = host.split(".")[0]
            cookie_dir = Path(settings.transcription_temp_dir) / "cookies"
            cookie_dir.mkdir(parents=True, exist_ok=True)
            cookie_path = cookie_dir / f"{domain}_playwright.txt"
            cookie_path.write_text(cookie_text, encoding="utf-8")
            logger.info("Cookie file created", path=str(cookie_path), cookie_count=len(cookies))

            return str(cookie_path)
        finally:
            await page.close()

    try:
        return asyncio.run(_run())
    except RuntimeError:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            return loop.run_until_complete(_run())
        finally:
            loop.close()


# ── Audio download ──


def _get_ffmpeg_path() -> str:
    """Get the ffmpeg executable path."""
    found = shutil.which("ffmpeg")
    return found or "ffmpeg"


def _download_and_extract_audio(
    video_url: str,
    audio_path: str,
    referer: str = "",
    cookie_header: str = "",
) -> None:
    """Download video from URL and extract audio to WAV using ffmpeg."""
    headers = f"User-Agent: {_USER_AGENT}"
    if referer:
        headers += f"\r\nReferer: {referer}"
    if cookie_header:
        headers += f"\r\nCookie: {cookie_header}"

    ffmpeg_cmd = [
        _get_ffmpeg_path(), "-y",
        "-headers", headers,
        "-i", video_url,
        *_FFMPEG_WAV_ARGS,
        audio_path,
    ]
    result = subprocess.run(
        ffmpeg_cmd,
        capture_output=True,
        text=True,
        timeout=1800,
        creationflags=_NO_WINDOW,
    )
    if result.returncode != 0:
        raise AudioExtractionError(
            f"ffmpeg audio download failed.\nURL: {video_url[:100]}\n"
            f"stderr: {result.stderr[:300]}"
        )


def extract_douyin_audio_advanced(url: str, output_path: str) -> dict:
    """Extract audio from a Douyin video URL using advanced Playwright extraction.

    1. Fetches rich metadata via Playwright (API interception + embedded JSON)
    2. Downloads audio via ffmpeg with proper headers (Referer + Cookie)
    3. Returns metadata dict for populating Video record

    Args:
        url: Douyin video URL
        output_path: Path to save the output WAV file

    Returns:
        dict: Rich metadata including id, title, duration, thumbnail, uploader, etc.

    Raises:
        AudioExtractionError: If extraction fails
    """
    logger.info("Extracting Douyin audio via advanced Playwright", url=url[:80])

    # Step 1: Fetch metadata
    video_data = fetch_douyin_video_data(url)

    title = video_data.get("title", "")
    video_url = video_data.get("video_url", "")
    duration = video_data.get("duration", 0)
    referer = f"https://www.douyin.com/video/{video_data.get('id', '')}"

    # Convert Playwright cookies to ffmpeg Cookie header
    netscape_cookies = video_data.get("cookies", "")
    cookie_header = _netscape_to_cookie_header(netscape_cookies)

    logger.info(
        "Playwright direct extraction",
        title=title,
        duration=f"{duration:.0f}s",
        video_url=video_url[:80],
    )

    if not video_url:
        raise AudioExtractionError("Playwright extracted no video URL")

    # Step 2: Download audio via ffmpeg
    try:
        _download_and_extract_audio(video_url, output_path, referer, cookie_header)
    except AudioExtractionError:
        raise
    except Exception as e:
        raise AudioExtractionError(f"Douyin audio download failed: {e}") from e

    if not Path(output_path).exists():
        raise AudioExtractionError("Audio extraction succeeded but output file not found")

    logger.info("Douyin audio extracted", path=output_path, size=os.path.getsize(output_path))

    # Return metadata (excluding raw cookies for cleanliness)
    metadata = {k: v for k, v in video_data.items() if k != "cookies"}
    metadata["source_url"] = url
    return metadata


# ── atexit cleanup ──

import atexit
atexit.register(close_browser)
