"""initial

Revision ID: 7db4e9d3fded
Revises: 
Create Date: 2026-05-30 14:47:25.658439
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '7db4e9d3fded'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('plan', sa.Enum('free', 'pro', name='plantype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('platform', sa.Enum('youtube', 'bilibili', 'other', name='platform'), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=2000), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('processing', 'ready', 'error', name='videostatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('video_url_480p', sa.String(length=2000), nullable=True),
    sa.Column('video_url_720p', sa.String(length=2000), nullable=True),
    sa.Column('video_url_1080p', sa.String(length=2000), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('topic_tags', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('words_learned', sa.Integer(), nullable=False),
    sa.Column('speaking_attempts', sa.Integer(), nullable=False),
    sa.Column('quiz_score', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_records_user_id'), 'learning_records', ['user_id'], unique=False)
    op.create_table('subtitles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.Column('text_zh', sa.Text(), nullable=True),
    sa.Column('sentence_index', sa.Integer(), nullable=False),
    sa.Column('grammar_note', sa.Text(), nullable=True),
    sa.Column('difficulty_words', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtitles_video_id'), 'subtitles', ['video_id'], unique=False)
    op.create_table('vocabulary',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('context_sentence', sa.Text(), nullable=True),
    sa.Column('video_id', sa.String(length=36), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_user_id'), 'vocabulary', ['user_id'], unique=False)
    op.create_table('speaking_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('subtitle_id', sa.String(length=36), nullable=False),
    sa.Column('audio_url', sa.String(length=2000), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('fluency', sa.Float(), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subtitle_id'], ['subtitles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speaking_attempts_user_id'), 'speaking_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speaking_attempts_user_id'), table_name='speaking_attempts')
    op.drop_table('speaking_attempts')
    op.drop_index(op.f('ix_vocabulary_user_id'), table_name='vocabulary')
    op.drop_table('vocabulary')
    op.drop_index(op.f('ix_subtitles_video_id'), table_name='subtitles')
    op.drop_table('subtitles')
    op.drop_index(op.f('ix_learning_records_user_id'), table_name='learning_records')
    op.drop_table('learning_records')
    op.drop_table('videos')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
