"""initial_schema

Revision ID: 80e681bd554d
Revises:
Create Date: 2026-06-22 08:31:58.747356
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers
revision: str = "80e681bd554d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invite_codes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("plan", sa.String(length=20), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("batch_label", sa.String(length=100), nullable=True),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("used_by", sa.String(length=36), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invite_codes_code"), "invite_codes", ["code"], unique=True)
    op.create_table(
        "speaking_rubrics",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("level", sa.String(length=10), nullable=True),
        sa.Column("plan", sa.Enum("free", "pro", name="plantype"), nullable=False),
        sa.Column("plan_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("role", sa.Enum("user", "admin", name="roletype"), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("onboarding_completed", sa.Boolean(), nullable=False),
        sa.Column("native_language", sa.String(length=10), nullable=False),
        sa.Column("avatar_url", sa.String(length=2000), nullable=True),
        sa.Column("bio", sa.String(length=300), nullable=True),
        sa.Column("timezone", sa.String(length=50), nullable=True),
        sa.Column("streak_count", sa.Integer(), nullable=False),
        sa.Column("longest_streak", sa.Integer(), nullable=False),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "daily_activities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("speaking_attempts", sa.Integer(), nullable=False),
        sa.Column("words_reviewed", sa.Integer(), nullable=False),
        sa.Column("words_added", sa.Integer(), nullable=False),
        sa.Column("videos_watched", sa.Integer(), nullable=False),
        sa.Column("quizzes_taken", sa.Integer(), nullable=False),
        sa.Column("avg_accuracy", sa.Float(), nullable=True),
        sa.Column("avg_fluency", sa.Float(), nullable=True),
        sa.Column("avg_completeness", sa.Float(), nullable=True),
        sa.Column("time_spent_seconds", sa.Integer(), nullable=False),
        sa.Column("goal_met", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="uq_daily_activity_user_date"),
    )
    op.create_index(op.f("ix_daily_activities_user_id"), "daily_activities", ["user_id"], unique=False)
    op.create_table(
        "follows",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("follower_id", sa.String(length=36), nullable=False),
        sa.Column("followee_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["followee_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["follower_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("follower_id", "followee_id", name="uq_follow"),
    )
    op.create_index(op.f("ix_follows_followee_id"), "follows", ["followee_id"], unique=False)
    op.create_index(op.f("ix_follows_follower_id"), "follows", ["follower_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("related_url", sa.String(length=500), nullable=True),
        sa.Column("data", sa.Text(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("order_number", sa.String(length=64), nullable=False),
        sa.Column("plan", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("pending", "paid", "expired", "cancelled", name="orderstatus"), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_order_number"), "orders", ["order_number"], unique=True)
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_password_reset_tokens_user_id"), "password_reset_tokens", ["user_id"], unique=False)
    op.create_table(
        "rubric_criteria",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("rubric_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rubric_id"],
            ["speaking_rubrics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_preferences",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "notification_preferences",
            sa.JSON(),
            nullable=True,
            comment="Dict of notification type -> bool opt-in. Null means all enabled.",
        ),
        sa.Column("daily_goal_type", sa.String(length=20), nullable=False),
        sa.Column("daily_goal_value", sa.Integer(), nullable=False),
        sa.Column("reminder_enabled", sa.Boolean(), nullable=False),
        sa.Column("reminder_time", sa.String(length=5), nullable=True),
        sa.Column("reminder_timezone", sa.String(length=50), nullable=True),
        sa.Column("auto_play_next_subtitle", sa.Boolean(), nullable=False),
        sa.Column("subtitle_mode_default", sa.String(length=20), nullable=False),
        sa.Column("preferred_difficulty", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_preferences_user_id"), "user_preferences", ["user_id"], unique=True)
    op.create_table(
        "videos",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("source_url", sa.String(length=2000), nullable=False),
        sa.Column("video_source", sa.Enum("local", "imported", name="videosource"), nullable=False),
        sa.Column("thumbnail_url", sa.String(length=2000), nullable=True),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("difficulty_level", sa.String(length=10), nullable=True),
        sa.Column(
            "status", sa.Enum("processing", "ready_subtitles", "ready", "error", name="videostatus"), nullable=False
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("processing_mode", sa.String(length=20), nullable=True),
        sa.Column("processing_step", sa.String(length=30), nullable=True),
        sa.Column("video_url_480p", sa.String(length=2000), nullable=True),
        sa.Column("video_url_720p", sa.String(length=2000), nullable=True),
        sa.Column("video_url_1080p", sa.String(length=2000), nullable=True),
        sa.Column("is_official", sa.Boolean(), nullable=False),
        sa.Column("topic_tags", sa.String(length=500), nullable=True),
        sa.Column("quiz_data", sa.JSON(), nullable=True),
        sa.Column("processing_progress", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "learning_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("words_learned", sa.Integer(), nullable=False),
        sa.Column("speaking_attempts", sa.Integer(), nullable=False),
        sa.Column("quiz_score", sa.Float(), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("time_spent_seconds", sa.Integer(), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("progress_percentage", sa.Float(), nullable=False),
        sa.Column("position_seconds", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "video_id", name="uq_learning_record_user_video"),
    )
    op.create_index(op.f("ix_learning_records_user_id"), "learning_records", ["user_id"], unique=False)
    op.create_table(
        "subtitles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("text_en", sa.Text(), nullable=False),
        sa.Column("text_zh", sa.Text(), nullable=True),
        sa.Column("sentence_index", sa.Integer(), nullable=False),
        sa.Column("speaker", sa.String(length=100), nullable=True),
        sa.Column("grammar_note", sa.Text(), nullable=True),
        sa.Column("difficulty_words", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subtitles_video_id"), "subtitles", ["video_id"], unique=False)
    op.create_table(
        "video_comment_stats",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("total_comments", sa.Integer(), nullable=False),
        sa.Column("total_likes", sa.Integer(), nullable=False),
        sa.Column("avg_comment_length", sa.Float(), nullable=False),
        sa.Column("learning_relevance_score", sa.Integer(), nullable=False),
        sa.Column("depth_score", sa.Integer(), nullable=False),
        sa.Column("engagement_score", sa.Integer(), nullable=False),
        sa.Column("overall_quality_score", sa.Integer(), nullable=False),
        sa.Column("keyword_stats", sa.JSON(), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("video_id"),
    )
    op.create_table(
        "video_comments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("video_id", sa.String(length=36), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("parent_id", sa.String(length=100), nullable=True),
        sa.Column("author_name", sa.String(length=255), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("reply_count", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("video_id", "external_id", name="uq_video_comment_external"),
    )
    op.create_index(op.f("ix_video_comments_video_id"), "video_comments", ["video_id"], unique=False)
    op.create_table(
        "vocabulary",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("word", sa.String(length=100), nullable=False),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.Column("translation", sa.String(length=500), nullable=True),
        sa.Column("part_of_speech", sa.String(length=20), nullable=True),
        sa.Column("ipa", sa.String(length=100), nullable=True),
        sa.Column("example_sentences", sa.JSON(), nullable=True),
        sa.Column("collocations", sa.JSON(), nullable=True),
        sa.Column("difficulty_level", sa.String(length=5), nullable=True),
        sa.Column("mastery_level", sa.String(length=20), nullable=False),
        sa.Column("context_sentence", sa.Text(), nullable=True),
        sa.Column("video_id", sa.String(length=36), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_review_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ease_factor", sa.Float(), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "word", name="uq_vocabulary_user_word"),
    )
    op.create_index(op.f("ix_vocabulary_user_id"), "vocabulary", ["user_id"], unique=False)
    op.create_table(
        "speaking_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("subtitle_id", sa.String(length=36), nullable=True),
        sa.Column("audio_url", sa.String(length=2000), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("accuracy", sa.Float(), nullable=True),
        sa.Column("fluency", sa.Float(), nullable=True),
        sa.Column("completeness", sa.Float(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("word_scores", sa.JSON(), nullable=True),
        sa.Column("audio_duration", sa.Float(), nullable=True),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("rubric_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["rubric_id"],
            ["speaking_rubrics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subtitle_id"],
            ["subtitles.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_speaking_attempts_user_id"), "speaking_attempts", ["user_id"], unique=False)
    op.create_table(
        "posts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("post_type", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("media_url", sa.String(length=2000), nullable=True),
        sa.Column("video_id", sa.String(length=36), nullable=True),
        sa.Column("speaking_attempt_id", sa.String(length=36), nullable=True),
        sa.Column("vocabulary_id", sa.String(length=36), nullable=True),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("comment_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["speaking_attempt_id"],
            ["speaking_attempts.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vocabulary_id"],
            ["vocabulary.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_posts_user_id"), "posts", ["user_id"], unique=False)
    op.create_table(
        "speaking_attempt_scores",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("speaking_attempt_id", sa.String(length=36), nullable=False),
        sa.Column("criterion_id", sa.String(length=36), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["criterion_id"],
            ["rubric_criteria.id"],
        ),
        sa.ForeignKeyConstraint(
            ["speaking_attempt_id"],
            ["speaking_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_speaking_attempt_scores_speaking_attempt_id"),
        "speaking_attempt_scores",
        ["speaking_attempt_id"],
        unique=False,
    )
    op.create_table(
        "post_likes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("post_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("post_id", "user_id", name="uq_post_like"),
    )
    op.create_index(op.f("ix_post_likes_post_id"), "post_likes", ["post_id"], unique=False)
    op.create_index(op.f("ix_post_likes_user_id"), "post_likes", ["user_id"], unique=False)
    op.create_table(
        "user_comments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("post_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("is_reported", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["user_comments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_comments_post_id"), "user_comments", ["post_id"], unique=False)
    op.create_index(op.f("ix_user_comments_user_id"), "user_comments", ["user_id"], unique=False)
    op.create_table(
        "comment_likes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("comment_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["user_comments.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("comment_id", "user_id", name="uq_comment_like"),
    )
    op.create_index(op.f("ix_comment_likes_comment_id"), "comment_likes", ["comment_id"], unique=False)
    op.create_index(op.f("ix_comment_likes_user_id"), "comment_likes", ["user_id"], unique=False)
    op.create_table(
        "comment_reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("comment_id", sa.String(length=36), nullable=False),
        sa.Column("reporter_id", sa.String(length=36), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["user_comments.id"],
        ),
        sa.ForeignKeyConstraint(["reporter_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comment_reports_comment_id"), "comment_reports", ["comment_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comment_reports_comment_id"), table_name="comment_reports")
    op.drop_table("comment_reports")
    op.drop_index(op.f("ix_comment_likes_user_id"), table_name="comment_likes")
    op.drop_index(op.f("ix_comment_likes_comment_id"), table_name="comment_likes")
    op.drop_table("comment_likes")
    op.drop_index(op.f("ix_user_comments_user_id"), table_name="user_comments")
    op.drop_index(op.f("ix_user_comments_post_id"), table_name="user_comments")
    op.drop_table("user_comments")
    op.drop_index(op.f("ix_post_likes_user_id"), table_name="post_likes")
    op.drop_index(op.f("ix_post_likes_post_id"), table_name="post_likes")
    op.drop_table("post_likes")
    op.drop_index(op.f("ix_speaking_attempt_scores_speaking_attempt_id"), table_name="speaking_attempt_scores")
    op.drop_table("speaking_attempt_scores")
    op.drop_index(op.f("ix_posts_user_id"), table_name="posts")
    op.drop_table("posts")
    op.drop_index(op.f("ix_speaking_attempts_user_id"), table_name="speaking_attempts")
    op.drop_table("speaking_attempts")
    op.drop_index(op.f("ix_vocabulary_user_id"), table_name="vocabulary")
    op.drop_table("vocabulary")
    op.drop_index(op.f("ix_video_comments_video_id"), table_name="video_comments")
    op.drop_table("video_comments")
    op.drop_table("video_comment_stats")
    op.drop_index(op.f("ix_subtitles_video_id"), table_name="subtitles")
    op.drop_table("subtitles")
    op.drop_index(op.f("ix_learning_records_user_id"), table_name="learning_records")
    op.drop_table("learning_records")
    op.drop_table("videos")
    op.drop_index(op.f("ix_user_preferences_user_id"), table_name="user_preferences")
    op.drop_table("user_preferences")
    op.drop_table("rubric_criteria")
    op.drop_index(op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_order_number"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_follows_follower_id"), table_name="follows")
    op.drop_index(op.f("ix_follows_followee_id"), table_name="follows")
    op.drop_table("follows")
    op.drop_index(op.f("ix_daily_activities_user_id"), table_name="daily_activities")
    op.drop_table("daily_activities")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("speaking_rubrics")
    op.drop_index(op.f("ix_invite_codes_code"), table_name="invite_codes")
    op.drop_table("invite_codes")
    # ### end Alembic commands ###
