"""add weekly_reports table for D9 weekly learning reports

Phase 2 D9 (产品设计规划-2026-08 §4): one row per user per ISO week with
aggregated study stats, generated by the Monday beat task. UNIQUE on
(user_id, week_start) makes generation idempotent.

Revision ID: d9e0f1g2h3i4
Revises: c6d7e8f9g0h1
Create Date: 2026-08-29 20:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers
revision: str = "d9e0f1g2h3i4"
down_revision: str | None = "c6d7e8f9g0h1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "weekly_reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("study_days", sa.Integer(), nullable=False),
        sa.Column("total_minutes", sa.Integer(), nullable=False),
        sa.Column("new_words", sa.Integer(), nullable=False),
        sa.Column("reviewed_words", sa.Integer(), nullable=False),
        sa.Column("videos_completed", sa.Integer(), nullable=False),
        sa.Column("streak_at_week_end", sa.Integer(), nullable=False),
        sa.Column("delta_minutes_pct", sa.Float(), nullable=True),
        sa.Column("daily_minutes", sa.JSON(), nullable=True),
        sa.Column("daily_new_words", sa.JSON(), nullable=True),
        sa.Column("highlight", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "week_start", name="uq_weekly_report_user_week"),
    )
    op.create_index("ix_weekly_reports_user_id", "weekly_reports", ["user_id"])
    op.create_index("ix_weekly_reports_week_start", "weekly_reports", ["week_start"])


def downgrade() -> None:
    op.drop_index("ix_weekly_reports_week_start", table_name="weekly_reports")
    op.drop_index("ix_weekly_reports_user_id", table_name="weekly_reports")
    op.drop_table("weekly_reports")
